name: Install and Build
on: [push]
jobs:
  Build-And-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pull And Deploy
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            exec bash
            cd pattieswap-front && git checkout main && git pull
            yarn && yarn build
            cp -rf build/* /var/www/pattieswap-front
